const QueryKeys = {
  student: ["student"],
  bulkStudent: ["bulkStudent"],
  boards: ["boards"],
  class: ["class"],
  stream: ["stream"],
  course: ["course"],
  examType: ["examType"],
  subject: ["subject"],
  chapter: ["chapter"],
  topic: ["topic"],
  concept: ["concept"],
  video: ["video"],
  quest: ["quest"],
  viewSyllabus: ["viewSyllabus"],
  AiBoardPaperFormat: ["AiBoardPaperFormat"],
  AiBoardQuest: ["AiBoardQuest"],
  studentScore: ["studentScore"],
  ts: ["ts"],
  examScore: ["examScore"],
  subscription: ["subscription"],
  teacher: ["teacher"],
  teacherAttendance: ["teacherAttendance"],
  teacherOtp: ["teacherOtp"],
  liveClass: ["liveClass"],
  deletedTeacher: ["deletedTeacher"],
  banner: ["banner"],
  parent: ["parent"],
  timeTable: ["timeTable"],
  stuChangeReq: "stuChangeReq",
  teacherChangeReq: "teacherChangeReq",
  parentChangeReq: "parentChangeReq",
  stuLeaveAppKeys: ["stuLeaveAppKeys"],
  eventKeys: ["event"],
  branchKey: ["branch"],
  notificationKey: ["notificationKey"],
};

export { QueryKeys };
